### ISSUE TITLE
java.io.IOException: ConnectNamedPipe() failed with: 535

### ISSUE THREAD

**Issue by dolly22** [sbt/ipcsocket#20]
I tried to upgrade to latest version (from 1.0.1 to 1.4.0) of the library and started getting this error sometimes.

```
    2021-10-05T07:46:06 ERR java.io.IOException: ConnectNamedPipe() failed with: 535
    2021-10-05T07:46:06 ERR 	at org.scalasbt.ipcsocket.Win32NamedPipeServerSocket.accept(Win32NamedPipeServerSocket.java:192)
```

The last working version that is not exhibiting this problem for me is 1.0.1. OS is windows 10.

Error code 535 is ERROR_PIPE_CONNECTED and it seems to me it [should be handled in the source](https://github.com/sbt/ipcsocket/blob/0d26720636a70cf25e6e4e225a9457e17d760a15/src/main/java/org/scalasbt/ipcsocket/Win32NamedPipeServerSocket.java#L172), but somehow it is not.

**Comment by eed3si9n** [comment]
Thanks for the report. We now have JNA and JNI implementations (for GraalVM JNI works better) so I wonder if the check is done one but not the other.

**Comment by dolly22** [comment]
@eed3si9n I searched in the source code and [this looks somewhat suspicious](https://github.com/sbt/ipcsocket/blob/0d26720636a70cf25e6e4e225a9457e17d760a15/src/main/java/org/scalasbt/ipcsocket/JNAWin32NamedPipeLibraryProvider.java#L235-L237). Do you think is't intentional?

```java
  @Override
  public int ERROR_PIPE_CONNECTED() {
    return WinError.ERROR_NO_DATA;
  }
```

**Comment by eed3si9n** [comment]
This was fixed in https://github.com/sbt/ipcsocket/pull/21
