### ISSUE TITLE
Issue with /tmp/.sbt/ipcsocket directory permission on a multi-user environment

### ISSUE THREAD

**Issue by MatteCarra** [sbt/ipcsocket#40]
When running for example sbtn on a given user, a temp '/tmp/.sbt/ipcsocket ' directory will be created and it will be owned by that user.
Any other user will be unable to run sbtn, because he will not have write permission on that folder.
The temp folder should be something like `/tmp/.sbt-$USER/ipcsocket` to avoid these kinds of issues.
The culprit is in https://github.com/sbt/ipcsocket/blob/ee3439303e592846168a3b18f23358d3c6665949/src/main/java/org/scalasbt/ipcsocket/NativeLoader.java

**Comment by eed3si9n** [comment]
This makes sense. I had to make a similar change on sbt/sbt side as well - https://github.com/sbt/sbt/pull/7042
