### ISSUE TITLE
java.io.IOException: WriteFile() failed: 6

### ISSUE THREAD

**Issue by bsideup** [sbt/ipcsocket#5]
Hi! I'm sometimes getting error code 6. Can it be a misconfiguration on my side, or is it a bug? Thanks!

Stacktrace:
```
java.io.IOException: WriteFile() failed: 6
            at org.scalasbt.ipcsocket.Win32NamedPipeSocket$Win32NamedPipeSocketOutputStream.write(Win32NamedPipeSocket.java:198)
```

**Comment by eed3si9n** [comment]
Closing this preemptively hoping it's now fixed. Let us know if this is still happening.
